#!/bin/bash

SRC_DIR="${0%/*}"
INCLUDE_DIR="$SRC_DIR"/include
GAWK_VERSION=$(gawk --version | gawk --source 'NR==1{print substr($3,0,length($3)-1)}')
GAWK_VERSION_MAJOR="${GAWK_VERSION%%.*}"

if [ $GAWK_VERSION_MAJOR -lt 5 ]; then
    echo "gawk 5.0.0 or higher required, found $GAWK_VERSION" >&2
    exit 1
fi

# Required to read the index file as bytes
export LC_ALL=C

export AWKPATH="$INCLUDE_DIR"
if [ -n "$TEST" ]; then
    echo "Testing"
    gawk -d -f "$SRC_DIR"/aho.awk -- "$@"
    echo "awkvars.out"
    grep -v '^[A-Z]*:' awkvars.out | sort -u
    rm awkvars.out
else
    exec gawk -f "$SRC_DIR"/aho.awk -- "$@"
fi
